Vagrant.configure("2") do |config|
  config.vm.box = "windows-2022-amd64"
  config.vm.communicator = "winrm"
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.network "forwarded_port", guest: 3389, host: 3389, id: "rdp", auto_correct: true
  
  config.vm.provider "libvirt" do |vb|
    vb.memory = 8192
    vb.cpus = 4
  end
  
  # Configure WinRM for Ansible
  config.winrm.username = "vagrant"
  config.winrm.password = "vagrant"
  config.winrm.transport = :plaintext
  config.winrm.basic_auth_only = true
  
# Provision with Ansible
config.vm.provision "ansible" do |ansible|
  ansible.playbook = "windows.yml"
  ansible.limit = "all"
  ansible.verbose = true
  # Windows-specific Ansible settings
  ansible.extra_vars = {
    ansible_connection: "winrm",
    ansible_winrm_transport: "basic",
    ansible_winrm_server_cert_validation: "ignore",
    ansible_user: "vagrant",
    ansible_password: "vagrant"
  }
end
end
